server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bp_demo
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false